language: python
python:
 # - "3.10"  # Specify the Python version you want to use

# Install dependencies
install:
  - pip install -r requirements.txt  # Install your project dependencies
  - pip install coverage coveralls black flake8  # Ensure tools are installed

# Script to run checks and tests
script:
  - black --check .  # Check code formatting
  - flake8 --max-line-length=88 .  # Linting for code style
  - coverage run -m pytest tests/test.py  # Run tests with coverage using pytest
  - env  # Print environment variables for debugging

# After successful builds, report coverage to Coveralls
after_success:
  - coveralls  # Report coverage to Coveralls

# Deployment to AWS Elastic Beanstalk
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ID
  secret_access_key: $AWS_KEY
  region: us-west-2
  app: SE_Assignment
  env: django-env-tuto-8
  bucket_name: elasticbeanstalk-us-west-2-886436937126
  skip_cleanup: true  # Avoid cleaning up before deploying
  on:
    branch: main  # Only deploy from the main branch
